"use client";

/**
 * Reads the text off a bill the user picked — a supplier's PDF or a phone photo — in the browser.
 *
 * Two engines, loaded on first use from jsDelivr so neither ships in the app bundle:
 *  - pdf.js for PDFs. Most suppliers' bills are generated by billing software and carry a real text
 *    layer, which is exact (no recognition errors) and instant. That covers the common case.
 *  - Tesseract for photos and scanned PDFs with no text layer. Slower (a few seconds a page) and
 *    fallible, which is why the form always shows the bill beside the fields it filled.
 *
 * Output is one string per printed row, top to bottom — the shape billParse.ts expects.
 */

const PDFJS_VERSION = "3.11.174";
const PDFJS_URL = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${PDFJS_VERSION}/build/pdf.min.js`;
const PDFJS_WORKER_URL = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${PDFJS_VERSION}/build/pdf.worker.min.js`;
const TESSERACT_URL = "https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js";

/** Pages read from one bill. A multi-page bill is rare; a 40-page PDF picked by mistake shouldn't hang. */
const MAX_PAGES = 5;

export interface BillText {
  rows: string[];
  source: "pdf-text" | "ocr";
}

type Progress = (message: string) => void;

// --- minimal typings for the two globals the UMD builds install ---
interface PdfTextItem {
  str: string;
  transform: number[];
  width: number;
  height: number;
}
interface PdfPage {
  getTextContent(): Promise<{ items: PdfTextItem[] }>;
  getViewport(o: { scale: number }): { width: number; height: number };
  render(o: { canvasContext: CanvasRenderingContext2D; viewport: unknown }): { promise: Promise<void> };
}
interface PdfDoc {
  numPages: number;
  getPage(n: number): Promise<PdfPage>;
}
interface PdfJs {
  GlobalWorkerOptions: { workerSrc: string };
  getDocument(src: { data: Uint8Array }): { promise: Promise<PdfDoc> };
}
interface TesseractWorker {
  recognize(image: HTMLCanvasElement | File | Blob | string): Promise<{ data: { text: string } }>;
  terminate(): Promise<void>;
}
interface TesseractLib {
  createWorker(lang: string, oem?: number, opts?: { logger?: (m: { status: string; progress: number }) => void }): Promise<TesseractWorker>;
}
declare global {
  interface Window {
    pdfjsLib?: PdfJs;
    Tesseract?: TesseractLib;
  }
}

const scripts = new Map<string, Promise<void>>();

function loadScript(src: string): Promise<void> {
  const cached = scripts.get(src);
  if (cached) return cached;
  const p = new Promise<void>((resolve, reject) => {
    const el = document.createElement("script");
    el.src = src;
    el.async = true;
    el.onload = () => resolve();
    el.onerror = () => {
      scripts.delete(src);
      reject(new Error("Couldn't load the bill reader. Check the internet connection and try again."));
    };
    document.head.appendChild(el);
  });
  scripts.set(src, p);
  return p;
}

async function pdfjs(): Promise<PdfJs> {
  await loadScript(PDFJS_URL);
  const lib = window.pdfjsLib;
  if (!lib) throw new Error("The PDF reader didn't start.");
  lib.GlobalWorkerOptions.workerSrc = PDFJS_WORKER_URL;
  return lib;
}

async function tesseract(onProgress?: Progress): Promise<TesseractWorker> {
  await loadScript(TESSERACT_URL);
  const lib = window.Tesseract;
  if (!lib) throw new Error("The text recogniser didn't start.");
  return lib.createWorker("eng", 1, {
    logger: (m) => {
      if (m.status === "recognizing text") onProgress?.(`Reading text… ${Math.round(m.progress * 100)}%`);
      else if (m.status) onProgress?.(`${m.status[0].toUpperCase()}${m.status.slice(1)}…`);
    },
  });
}

export async function readBillText(file: File, onProgress?: Progress): Promise<BillText> {
  const isPdf = file.type === "application/pdf" || /\.pdf$/i.test(file.name);
  if (isPdf) return readPdf(file, onProgress);
  if (file.type.startsWith("image/")) return readImage(file, onProgress);
  throw new Error("Pick a PDF or an image of the bill.");
}

async function readPdf(file: File, onProgress?: Progress): Promise<BillText> {
  onProgress?.("Opening PDF…");
  const lib = await pdfjs();
  const doc = await lib.getDocument({ data: new Uint8Array(await file.arrayBuffer()) }).promise;
  const pages = Math.min(doc.numPages, MAX_PAGES);

  const rows: string[] = [];
  for (let n = 1; n <= pages; n++) {
    const page = await doc.getPage(n);
    const { items } = await page.getTextContent();
    rows.push(...groupRows(items));
  }

  // A scanned PDF is a picture in a PDF wrapper — no text layer, so recognise the rendered pages.
  const letters = rows.join("").replace(/\s/g, "").length;
  if (letters >= 40) return { rows, source: "pdf-text" };

  const worker = await tesseract(onProgress);
  try {
    const ocrRows: string[] = [];
    for (let n = 1; n <= pages; n++) {
      onProgress?.(`Scanning page ${n} of ${pages}…`);
      const page = await doc.getPage(n);
      const viewport = page.getViewport({ scale: 2 });
      const canvas = document.createElement("canvas");
      canvas.width = viewport.width;
      canvas.height = viewport.height;
      const ctx = canvas.getContext("2d");
      if (!ctx) continue;
      await page.render({ canvasContext: ctx, viewport }).promise;
      const { data } = await worker.recognize(canvas);
      ocrRows.push(...splitRows(data.text));
    }
    return { rows: ocrRows, source: "ocr" };
  } finally {
    await worker.terminate();
  }
}

async function readImage(file: File, onProgress?: Progress): Promise<BillText> {
  const worker = await tesseract(onProgress);
  try {
    const { data } = await worker.recognize(file);
    return { rows: splitRows(data.text), source: "ocr" };
  } finally {
    await worker.terminate();
  }
}

function splitRows(text: string): string[] {
  return text.split(/\r?\n/).map((r) => r.replace(/\s+/g, " ").trim()).filter(Boolean);
}

/**
 * pdf.js hands back loose text runs with coordinates, not lines. Runs whose baselines sit within
 * half a line of each other belong to the same printed row; within a row they're read left to right,
 * with a space wherever there is a visible gap.
 */
function groupRows(items: PdfTextItem[]): string[] {
  const runs = items
    .filter((i) => i.str && i.str.trim())
    .map((i) => ({ text: i.str, x: i.transform[4], y: i.transform[5], w: i.width, h: Math.abs(i.height) || Math.abs(i.transform[3]) || 8 }));
  runs.sort((a, b) => b.y - a.y || a.x - b.x);

  const rows: (typeof runs)[] = [];
  for (const r of runs) {
    const row = rows[rows.length - 1];
    const tol = Math.max(2, r.h * 0.5);
    if (row && Math.abs(row[0].y - r.y) <= tol) row.push(r);
    else rows.push([r]);
  }

  return rows
    .map((row) => {
      row.sort((a, b) => a.x - b.x);
      let out = "";
      let end = -Infinity;
      for (const r of row) {
        const gap = r.x - end;
        out += out && gap > Math.max(1, r.h * 0.15) ? ` ${r.text}` : r.text;
        end = r.x + r.w;
      }
      return out.replace(/\s+/g, " ").trim();
    })
    .filter(Boolean);
}
