"use client";

import { PayrollShell, PayrollEmpty } from "@/components/payroll/PayrollShell";
import { Spinner } from "@/components/Spinner";
import { useMyPayslips } from "@/lib/usePayrollLive";
import type { PayslipApi } from "@/lib/api";
import { inr } from "@/lib/format";
import { downloadPayslip } from "@/lib/payslipExport";
import { Download, Wallet } from "lucide-react";

/**
 * My Payslips — the signed-in member's own payslips, generated by real monthly runs. Each row is
 * one month; PDF download uses the same shared PDF utility as everything else in the app.
 */
const MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
function fmtMonth(month: string | null): string {
  if (!month) return "Payslip";
  const [y, m] = month.split("-").map(Number);
  return m >= 1 && m <= 12 ? `${MONTH_NAMES[m - 1]} ${y}` : month;
}

export default function MyPayslipsPage() {
  const { slips, loading, error } = useMyPayslips();

  function slipPdf(p: PayslipApi) {
    downloadPayslip(p, p.memberName);
  }

  return (
    <PayrollShell>
      <div className="space-y-4">
        <div>
          <h2 className="text-lg font-semibold text-gray-800">My Payslips</h2>
          <p className="mt-0.5 text-sm text-gray-500">Your monthly pay, generated when payroll runs. Download any slip as a PDF.</p>
        </div>

        {error && <div className="rounded-lg bg-rose-50 px-4 py-2 text-sm text-rose-600">{error}</div>}

        {loading ? (
          <div className="flex items-center justify-center gap-2 rounded-xl border border-dashed border-gray-300 bg-white py-16 text-sm text-gray-400">
            <Spinner size={16} className="text-brand-accent" /> Loading…
          </div>
        ) : slips.length === 0 ? (
          <PayrollEmpty icon={Wallet} title="No payslips yet" hint="Once HR runs payroll for a month, your slip lands here." />
        ) : (
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {slips.map((p) => (
              <div key={p.id} className="rounded-xl border border-gray-200 bg-white p-4 transition-shadow hover:shadow-sm">
                <div className="flex items-start justify-between">
                  <div>
                    <div className="text-sm font-semibold text-gray-800">{fmtMonth(p.month)}</div>
                    <div className="mt-0.5 text-[11px] text-gray-400">{p.payableDays} of {p.totalDays} days</div>
                  </div>
                  <div className="flex h-9 w-9 items-center justify-center rounded-full bg-cyan-50 text-brand-accent"><Wallet size={16} /></div>
                </div>
                <div className="mt-3 flex items-end justify-between">
                  <div>
                    <div className="text-[11px] tracking-wide text-gray-400 uppercase">Net Pay</div>
                    <div className="text-xl font-semibold text-gray-900">{inr(p.net)}</div>
                  </div>
                  <button onClick={() => slipPdf(p)} className="flex items-center gap-1 rounded-lg border border-gray-200 px-2.5 py-1.5 text-xs font-medium text-gray-600 transition-colors hover:border-brand-accent hover:text-brand-accent">
                    <Download size={13} /> PDF
                  </button>
                </div>
                <div className="mt-3 grid grid-cols-3 gap-2 border-t border-gray-100 pt-2 text-[11px] text-gray-500">
                  <span>Gross {inr(p.gross)}</span>
                  <span>Ded {inr(Number(p.pf) + Number(p.esic) + Number(p.pt) + Number(p.loanEmi))}</span>
                  <span>{p.payableDays}/{p.totalDays} days</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </PayrollShell>
  );
}
