"use client";

import { PayrollShell, PayrollEmpty } from "@/components/payroll/PayrollShell";
import { Spinner } from "@/components/Spinner";
import { useMyPayslips } from "@/lib/usePayrollLive";
import { useAuthStore } from "@/lib/authStore";
import { usePayrollProfiles } from "@/lib/usePayrollSetup";
import { useEffect, useState } from "react";
import { myPaymentsApi } from "@/lib/api";
import type { PaymentApi, PayslipApi } from "@/lib/api";
import { formatDateIST } from "@/lib/datetime";
import { inr } from "@/lib/format";
import { downloadPayslip, leaveSummary } from "@/lib/payslipExport";
import { Download, Wallet } from "lucide-react";

/**
 * My Payslips — the signed-in member's own payslips, generated by real monthly runs. Each row is
 * one month; PDF download uses the same shared PDF utility as everything else in the app.
 */
const MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
function fmtMonth(month: string | null): string {
  if (!month) return "Payslip";
  const [y, m] = month.split("-").map(Number);
  return m >= 1 && m <= 12 ? `${MONTH_NAMES[m - 1]} ${y}` : month;
}

export default function MyPayslipsPage() {
  const { slips, loading, error } = useMyPayslips();
  // The member's own profile, so their slip carries designation, PAN and bank account like the one
  // payroll downloads for them — not a column of dashes.
  const myId = useAuthStore((s) => s.user?.id);
  const { profiles } = usePayrollProfiles(myId != null ? [Number(myId)] : undefined);

  const [payments, setPayments] = useState<PaymentApi[]>([]);
  useEffect(() => { myPaymentsApi().then(setPayments).catch(() => setPayments([])); }, []);

  function slipPdf(p: PayslipApi) {
    downloadPayslip(p, p.memberName, { profile: profiles[p.userId] });
  }

  return (
    <PayrollShell>
      <div className="space-y-4">
        <div>
          <h2 className="text-lg font-semibold text-gray-800">My Payslips</h2>
          <p className="mt-0.5 text-sm text-gray-500">Your monthly pay, generated when payroll runs. Download any slip as a PDF.</p>
        </div>

        {error && <div className="rounded-lg bg-rose-50 px-4 py-2 text-sm text-rose-600">{error}</div>}

        {loading ? (
          <div className="flex items-center justify-center gap-2 rounded-xl border border-dashed border-gray-300 bg-white py-16 text-sm text-gray-400">
            <Spinner size={16} className="text-brand-accent" /> Loading…
          </div>
        ) : slips.length === 0 ? (
          <PayrollEmpty icon={Wallet} title="No payslips yet" hint="Once HR runs payroll for a month, your slip lands here." />
        ) : (
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {slips.map((p) => (
              <div key={p.id} className="rounded-xl border border-gray-200 bg-white p-4 transition-shadow hover:shadow-sm">
                <div className="flex items-start justify-between">
                  <div>
                    <div className="text-sm font-semibold text-gray-800">{fmtMonth(p.month)}</div>
                    <div className="mt-0.5 text-[11px] text-gray-400">{p.payableDays} of {p.totalDays} days</div>
                  </div>
                  <div className="flex h-9 w-9 items-center justify-center rounded-full bg-cyan-50 text-brand-accent"><Wallet size={16} /></div>
                </div>
                <div className="mt-3 flex items-end justify-between">
                  <div>
                    <div className="text-[11px] tracking-wide text-gray-400 uppercase">Net Pay</div>
                    <div className="text-xl font-semibold text-gray-900">{inr(p.net)}</div>
                  </div>
                  <button onClick={() => slipPdf(p)} className="flex items-center gap-1 rounded-lg border border-gray-200 px-2.5 py-1.5 text-xs font-medium text-gray-600 transition-colors hover:border-brand-accent hover:text-brand-accent">
                    <Download size={13} /> PDF
                  </button>
                </div>
                <div className="mt-3 grid grid-cols-3 gap-2 border-t border-gray-100 pt-2 text-[11px] text-gray-500">
                  <span>Gross {inr(p.gross)}</span>
                  <span>Ded {inr(Number(p.gross) - Number(p.net) + Number(p.reimbursements))}</span>
                  <span className={p.payStatus === "PAID" ? "font-medium text-emerald-600" : ""}>{p.payStatus === "PAID" ? "Paid" : p.holdStatus ? "On hold" : "Pending"}</span>
                </div>
                {(leaveSummary(p) || p.claimDetail) && (
                  <div className="mt-2 space-y-0.5 text-[11px] text-gray-500">
                    {leaveSummary(p) && <div>Leave: <span className="text-gray-700">{leaveSummary(p)}</span></div>}
                    {p.claimDetail && <div>Claims reimbursed: <span className="text-gray-700">{p.claimDetail}</span></div>}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {payments.length > 0 && (
          <div className="rounded-xl border border-gray-200 bg-white">
            <div className="border-b border-gray-100 px-4 py-2 text-sm font-semibold text-gray-800">Payments received</div>
            <table className="w-full text-sm">
              <tbody>
                {payments.map((x) => (
                  <tr key={x.id} className="border-t border-gray-50 first:border-t-0">
                    <td className="px-4 py-2">{formatDateIST(x.recordDate)}</td>
                    <td className="px-4 py-2 text-gray-600">{x.category === "ADVANCE" ? "Advance salary" : x.category === "SALARY" ? "Salary" : x.category.charAt(0) + x.category.slice(1).toLowerCase()} · {fmtMonth(x.month)}</td>
                    <td className="px-4 py-2 text-xs text-gray-500">{x.mode}</td>
                    <td className="px-4 py-2 text-right font-medium">{inr(x.amount)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </PayrollShell>
  );
}
